name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Install and Build 
        shell: bash -l {0}
        run: |
          conda env create --file requirements.yml
          conda activate pelican
          make publish

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: output